os: osx
language: node_js
sudo: false
node_js:
  - 8.11.1
addons:
  apt:
    packages:
      - oracle-java8-set-default

before_script:
  - mv sample.env .env
  - npm install
  - node nightwatch.conf.js

script:
  - npm test
