version: 2
jobs:
  test:
    docker:
      - image: "circleci/node:8.11.1"
    steps:
      - checkout
      - run: 
          shell: /bin/sh
          command: |
            mv sample.env .env
            npm install
            node nightwatch.conf.js
            npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test